import Vue from 'vue'
import VueI18n from 'vue-i18n'
const messages = {
  zh: {
    power: '我的算力',
    balance: '我的余额',
    supply: '全网流通通证',
    burnToken: '燃烧挖矿合约',
    levelDesc: '等级说明',
    oldPower: '老合约算力',
    langShortZh: '中',
    langEn: 'English',
    langZh: '中文',
    income: '挖矿年化收益',
    contractAddress: '合约地址',
    burn: '燃烧原料',
    received: '明日再来',
    upgradePower: '升级算力',
    upgrade: '升级',
    pledgeAmount: '质押数量',
    // received: '升级中',
    uploading: '升级中，敬请期待！！',
    binder: '是否绑定邀请人',
    yes: '是',
    asInviter: '为邀请人',
    drag: '挖取矿产',
    prevDragTime: '上次领取奖励',
    nextDragTime: '下次挖矿时间',
    rewardTotal: '累计邀请收益',
    globalPower: '全网流通',
    divRule: '减产机制',
    divRules: '每24小时，周期增加236秒，第一年减50%，第二年减33%第三年减25%',
    ruleDesc: '规则说明',
    invite: '邀请好友',
    organization: '审计机构',
    joinUs: '加入我们',
    usedBalance: '可用余额',
    all: '全部',
    burnBtn: '确定燃烧',
    burnDesc: '燃烧=销毁，1{tokenSymbol}可燃烧出价值3{tokenSymbol}的算力',
    totalInvite: '共邀请{amount}人',
    myAddress: '我的地址',
    bindInviter:'绑定邀请人',
    binded: '已绑定',
    bindBtn: '确定绑定',
    todayAmount: '今日收益',
    getBtn: '确定领取',
    getDesc: '高级矿工最高可累积30天领取收益',
    receiveIncome: '领取收益',
    notStart: '暂时还未开放挖矿！',
    whitepaper: '白皮书下载',
    receivedTimeCalc: '领取时间计算器',
    receivedTimeCalcTips: '本计算仅供参考',
    Cumulative: '第',
    receivedTime: '次领取时间',
    showMore: '显示30次领取时间',
    hideMore: '显示7次领取时间',
    powerRank: '算力排行榜',
    index: '排名',
    username: '用户',
    powerCol: '算力',
    awardCol: '奖励',
    inviteRank: '邀请排行榜',
    rank: '排行榜',
    myInvite: '我的好友',
    noInvite: '无数据',
    loadMore: '加载更多',
    noMore: '没有更多了',
    friends: '好友',
    receiveAirdrop: '领取空投',
    airdropAmount: '空投数量',
    totalLiquitityPledge: '全网{symbol}总质押量',
    totalAddress: '全网参与地址数',
    pledge: '质押',
    unlockPledge: '取出',
    unlockPledgeAmount: '取出数量',
    invitePlaceholder:'请输入你邀请人的地址',
    minPledgeRule: '温馨提示: 需要最少质押{minAmount}个{pledgeTokenSymbol}才可以参与挖矿,随着 {tokenSymbol} 价格上升，会提高质押门槛。',
    minPledgeRule1: '温馨提示: 需要最少质押{minAmount}个{pledgeTokenSymbol}和{minAmount1}个{pledgeTokenSymbol2}才可以参与挖矿,随着 {tokenSymbol} 价格上升，会提高质押门槛。',
    nowPledgeAmount: '现质押{pledgeAmount}{plageName}',
    withdrawRule: '取出资产需要在上次挖矿后24小时',
    addressPlaceholder: '请输入绑定邀请的地址',
    notOwner: '不能绑定自己！',
    notContract: '不能绑定合约地址为邀请人！',
    bindSuccess: '绑定成功',
    amountPlaceholder: '请输入您的数量',
    coinPlaceholder: '请选择质押币种',
    operateSuccess: '操作成功',
    received1:'您今天已经领取过收益了,明天再来！',
    receivedSuccess: '收益领取成功！',
    blockSuccess: '区块打包成功',
    error: '错误:',
    gasEmpty: '矿工费不足',
    cancel: '取消',
    nodeError: '节点异常，请切换节点',
    unnormal: '异常',
    join: '立即加入',
    chCommunity: '中文社群',
    authentication: '知道创宇云安全认证',
    transfromFeeDesc: '转账手续费销毁功能',
    ok: '好的',
    burnTips: '确定提交后你燃烧的余额将销毁变成3倍算力',
    burnTips2: '燃烧的时候会燃烧一定比例的{tokenSymbol}，具体由社区dao决定',
    leveTips: '等级达到Lv2,产出收益最多累计{time}次',
    pledgeTips: '等级小于V1的用户最少质押{minAmount}的{symbol}才可进行挖矿',
    noPower: '您当前还没有算力！',
    airdropNotStart: '空投活动还未开始',
    zeroAirdrop: '我的算力为0才可以参加领取空投活动！',
    airdropSuccess: '空投领取成功，等待10秒后刷新即可看到算力！',
    notUpgrade: '现在还不能升级',
    zeroUpgrade: '算力为0才可以升级！',
    upgradeSuccess: '升级成功！',
    oneDayDrag: '取出质押需要在上次挖矿后24小时!',
    waitFeedback: '提交请求成功，等待区块确认',
    pledging: '质押中',
    permission: '权限申请中',
    qusd:'稳定币质押，年化apy收益100%+',
    teamPowers: '团队总算力',
    teams: '发展委',
    bigTeamPowers: '大区算力',
    smallTeamPowers: '小区算力',
    bigTeamFriend: '大区好友',
    smallTeamFriend: '小区好友',
    personUnit: '名',
    walletAddress: '钱包地址'
  },
  en: {
    power: 'My Power',
    balance: 'Balance',
    supply: 'Supply',
    burnToken: 'Burn Token',
    levelDesc: 'Level',
    oldPower: 'Old Token Power',
    langShortZh: 'EN',
    langEn: 'EN',
    langZh: '中文',
    income: 'Annual Mining Income',
    contractAddress: 'Contract Address',
    burn: 'Burn',
    received: 'Mined today',
    upgradePower: 'Upgrade',
    upgrade: 'Upgrade',
    pledgeAmount: 'Pledge Amount',
    // received: 'Upgrading',
    uploading: 'The project is being upgraded, so stay tuned.',
    binder: 'Whether to bind the inviter',
    yes: 'Yes',
    asInviter: 'For the inviter',
    drag: 'Mining',
    prevDragTime: 'Mined Time',
    nextDragTime: 'Next Mining Time',
    rewardTotal: 'Cumulative Invite Income',
    globalPower: 'Total Supply',
    divRule: 'Production Reduction Mechanism',
    divRules: 'Every 24 hours, the cycle increases by 236 seconds, the first year is reduced by 50%, the second year is reduced by 33%, and the third year is reduced by 25%',
    ruleDesc: 'Rule Description',
    invite: 'Invite Friends',
    organization: 'Audit Agency',
    joinUs: 'Join Us',
    usedBalance: 'Available Balance',
    all: 'All',
    burnBtn: 'Submit Burn',
    burnDesc: 'Burning = destruction, 1{tokenSymbol}  can burn 3{tokenSymbol} worth of computing power',
    totalInvite: 'Total Invitation {amount} People',
    myAddress: 'My Address',
    bindInviter:'Bind Inviter',
    binded: 'Bound',
    bindBtn: 'Submit Bind',
    todayAmount: "Today's Earnings",
    getBtn: 'submit Receive',
    getDesc: 'Advanced miners can accumulate up to 30 days to receive income',
    receiveIncome: 'Receive income',
    notStart: 'Mining is not yet open!',
    whitepaper: 'Download',
    receivedTimeCalc: 'Receiving Time Calculator',
    receivedTimeCalcTips: 'This Calculation Is For Reference Only',
    Cumulative: '',
    receivedTime: ' Times Receiving Time',
    showMore: 'Show More',
    hideMore: 'Hidden',
    powerRank: 'Computing Power Rankings',
    index: 'Rank',
    username: 'Username',
    powerCol: 'Power',
    awardCol: 'Reward',
    inviteRank: 'Invitation Rankings',
    rank: 'Rankings',
    myInvite: 'My Friends',
    noInvite: 'No Data',
    loadMore: 'Load More',
    noMore: 'No More',
    friends: 'Friends',
    receiveAirdrop: 'Receive airdrop',
    airdropAmount: 'Amount',
    totalLiquitityPledge: '{symbol} Total liquidity pledge',
    totalAddress: 'Total Address',
    pledge: 'Pledge',
    unlockPledge: 'Unlock pledge',
    unlockPledgeAmount: 'Unlock pledge amount',
    invitePlaceholder:'Input address',
    minPledgeRule: 'You need to pledge at least {minUbt}{plageName} to receive mining revenue',
    minPledgeRule1: 'You need to pledge at least {minUbt}{plageName} and to {minAmount1}{pledgeTokenSymbol2} receive mining revenue',
    nowPledgeAmount: 'Now pledge {pledgeAmount}{plageName}',
    withdrawRule: 'Withdrawal of assets requires 24 hours after the last mining',
    addressPlaceholder: 'Please enter the address of the binding invitation',
    notOwner: "Can't bind yourself!",
    notContract: 'Cannot bind the contract address as the inviter!',
    bindSuccess: 'Bind successfully',
    amountPlaceholder: 'Please enter your quantity',
    coinPlaceholder: 'Please choose Token',
    operateSuccess: 'Successful operation',
    received1:'You have already received the income today, come back tomorrow!',
    receivedSuccess: 'The income is successfully received!',
    blockSuccess: 'Block package successfully',
    error: 'error:',
    gasEmpty: 'Insufficient miner fees',
    cancel: 'cancel transaction',
    nodeError: 'Node is abnormal, please switch node',
    unnormal: 'Abnormal',
    join: 'Join',
    chCommunity: 'Chinese community',
    authentication: 'ZhiDaoChuangYu Safety Certification',
    transfromFeeDesc: 'Transfer Fee Introduction',
    ok: 'OK',
    burnTips: 'Make sure that the balance you burn after submitting will be destroyed and become 3 times the computing power',
    burnTips2: 'When burning, it will burn a certain proportion of {tokenSymbol}, which is determined by the community dao',
    leveTips: 'The level reaches Lv2, and the output income is up to {time} times',
    pledgeTips: 'Users with a level of less than V1 can only deposit {symbol} with the least {minAmount} pledge',
    noPower: 'You currently have no computing power!',
    airdropNotStart: 'The airdrop has not yet started',
    zeroAirdrop: 'My computing power is 0 before I can participate in the airdrop activity!',
    airdropSuccess: 'The airdrop is successfully received, wait for 10 seconds and then refresh to see the hashrate!',
    notUpgrade: "Can't upgrade yet",
    zeroUpgrade: 'You can upgrade only if the computing power is 0!',
    upgradeSuccess: 'Success',
    oneDayDrag: 'It takes 24 hours after the last mining to take out the pledge',
    waitFeedback: 'Submit the request successfully, waiting for block confirmation',
    pledging: 'Pledeing',
    permission: 'Permission application',
    qusd:'Stable currency pledge, annual income 100%+',
    teamPowers: 'Team Powers',
    teams: 'Key Opinion Leader',
    bigTeamPowers: '大区算力',
    smallTeamPowers: '小区算力',
    bigTeamFriend: '大区好友',
    smallTeamFriend: '小区好友',
    personUnit: '名',
    walletAddress: '钱包地址'
  }
}
Vue.use(VueI18n);
const i18n = new VueI18n({
  locale: localStorage.getItem('APP_LANG') || 'zh', // set locale
  silentFallbackWarn: true,
  messages, // set locale messages
})

export default i18n


// import Vue from 'vue'
// import VueI18n from 'vue-i18n'
// import { APP_LANG } from '@/commons/const'
// import zh from './zh'
// import en from './en'

// Vue.use(VueI18n)
// const i18n = new VueI18n({
//   locale: localStorage.getItem(APP_LANG) || 'en',
//   silentFallbackWarn: true,
//   messages: {
//     en,
//     zh,
//   },
// })

// export default i18n
